Repository zapify-ui/zapify, pull requests merged in 2019-08, with the labels that each got.

#4 Input button piyush97
  src/App.jsx
  src/App.scss
  src/Component/Inputs/Buttons/Buttons.jsx
  src/Component/Inputs/Buttons/styles.scss
  src/Component/Layout/Box/Box.jsx
  src/Styles/globals.scss
Labels: enhancement

#5 Box vinaybiradar1717
  src/App.jsx
  src/Component/Inputs/Buttons/styles.css
  src/Component/Inputs/Buttons/styles.css.map
  src/Component/Layout/Box/Box.jsx
  src/Component/Layout/Box/boxStyles.css
  src/Component/Layout/Box/boxStyles.css.map
  src/Component/Layout/Box/boxStyles.scss
  src/Component/Layout/Container/Container.jsx
  src/Component/Layout/Container/containerStyles.css
  src/Component/Layout/Container/containerStyles.css.map
  src/Component/Layout/Container/containerStyles.scss
  src/Styles/globals.scss
Labels: enhancement

#7 Create README.md
  README.md
Labels: documentation

#23 Piyush97 appbar
  src/components/AppBar/AppBar.scss
  src/components/AppBar/index.js
  src/components/Grid/index.js
  src/components/Media/index.js
  src/components/TextFieldHook/index.js
  src/components/index.js
  src/stories/appbar.stories.js
  src/stories/box.stories.js
  src/stories/textfieldhook.stories.js
Labels: Component Made, Refactor, documentation, enhancement

#25 resolved bug fix
  src/components/AppBar/AppBar.scss
Labels: Bug fix

#27 Boxing box restructured
  src/components/Box/index.js
  src/components/index.js
  src/stories/box.stories.js
Labels: Refactor

#28 story
  package-lock.json
  package.json
  src/.storybook/addons.js
  src/.storybook/config.js
  src/components/ZapBar/ZapBar.scss
  src/stories/box.stories.js
  src/stories/zapbar.stories.js
  webpack.config.js
Labels: Refactor

#33 Readme
  README.md
Labels: documentation

#41 Testing components
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  package-lock.json
  package.json
  src/components/Box/__snapshots__/box.test.js.snap
  src/components/Box/box.test.js
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Container/Container.test.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/Media/Media.test.js
  src/components/Media/__snapshots__/Media.test.js.snap
  yarn.lock
Labels: Testing

#43 Readme My name 😜
  README.md
Labels: documentation

#44 Testing components
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  babel.config.js
  package-lock.json
  package.json
  src/components/Box/__snapshots__/box.test.js.snap
  src/components/Box/box.test.js
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Container/Container.test.js
  src/components/Container/__snapshots__/Container.test.js.snap
  src/components/Media/Media.test.js
  src/components/Media/__snapshots__/Media.test.js.snap
  yarn.lock
Labels: Testing

#45 Text box
  src/components/TextField/TextField.scss
  src/components/TextField/index.js
  src/components/TextFieldHook/TextFieldHook.scss
  src/components/TextFieldHook/index.js
  src/components/ZapBar/index.js
  src/components/index.js
  src/stories/textfield.stories.js
  src/stories/textfieldhook.stories.js
Labels: enhancement

#46 added tests
  package-lock.json
  src/components/TextField/TextField.test.js
  src/components/TextField/__snapshots__/TextField.test.js.snap
  src/components/Typography/Typography.test.js
  src/components/Typography/__snapshots__/Typography.test.js.snap
  src/components/ZapBar/ZapBar.test.js
  src/components/ZapBar/__snapshots__/ZapBar.test.js.snap
Labels: Testing

#47 Typography Dynamically fixed with props and default props
  src/components/Typography/Typography.test.js
  src/components/Typography/__snapshots__/Typography.test.js.snap
  src/components/Typography/index.js
  src/stories/textfield.stories.js
  src/stories/typography.stories.js
Labels: enhancement

#48 Box refactor
  .gitignore
  src/components/Box/__snapshots__/box.test.js.snap
  src/components/Box/index.js
  src/components/Typography/Typography.scss
  src/components/Typography/__snapshots__/Typography.test.js.snap
  src/components/Typography/index.js
  src/stories/box.stories.js
  src/stories/typography.stories.js
Labels: Refactor

#49 Storybook
  .travis.yml
  src/.storybook/config.js
  src/.storybook/zapify.js
  src/components/TextField/TextField.test.js
  src/components/ZapBar/ZapBar.test.js
  src/stories/typography.stories.js
Labels: enhancement

#51 Card component
  src/components/Card/Card.scss
  src/components/Card/index.js
  src/components/Card1/Card1.scss
  src/components/Card1/index.js
  src/components/index.js
  src/stories/card.stories.js
  src/stories/card1.stories.js
Labels: Component Made, enhancement

#56 Grid Implementation
  src/components/Box/index.js
  src/components/Grid/Grid.scss
  src/components/Grid/index.js
  src/components/InfoCard/InfoCard.scss
  src/components/InfoCard/index.js
  src/stories/grid.stories.js
  src/stories/infocard.stories.js
  src/styles/ColorSchema.scss
Labels: Component Made, enhancement

#58 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#61 4k support
  src/components/Grid/Grid.scss
Labels: Bug fix

#64 Vinay buttons
  .gitignore
  .npmignore
  package-lock.json
  src/components/Button/Button.scss
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/Button/index.js
  src/components/ZapButton/ZapButton.scss
  src/components/ZapButton/index.js
  src/components/index.js
  src/stories/button.stories.js
  src/stories/components.stories.js
  src/stories/zapbutton.stories.js
Labels: Component Made, enhancement

#65 Zapbutton
  src/components/ZapButton/ZapButton.scss
  src/stories/zapbutton.stories.js
  src/styles/ColorSchema.scss
Labels: enhancement

#67 Res
  src/components/Card/Card.scss
  src/components/InfoCard/InfoCard.scss
Labels: Refactor

#75 zapbuttons modified
  src/components/ZapButton/ZapButton.scss
  src/stories/zapbutton.stories.js
  src/styles/ColorSchema.scss
  storybook-static/index.html
  storybook-static/main.6901342adfe312e752bd.bundle.js
  storybook-static/runtime~main.ba735fcc62253c47f409.bundle.js
  storybook-static/vendors~main.86302694b075f4d1a80f.bundle.js
Labels: enhancement
